measurely-api/archive/scala-api/config/routes.rb
Rails.application.routes.draw do
  root 'home#show'
  get 'home/show'
  get 'auth/oauth2/callback' => 'auth0#callback'
  get 'auth/failure' => 'auth0#failure'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :scale
  match 'scale', to: 'scale#update', via: [:patch, :put]
  resources :clients
  match 'clients', to: 'clients#update', via: [:patch, :put]
  # root :to => 'scale#index'
end

measurely-api/archive/scala-api/app/models/analytics_posttherapy.rb
class AnalyticsPosttherapy < ApplicationRecord
end

measurely-api/archive/scala-api/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

measurely-api/archive/scala-api/app/models/client.rb
class Client < ApplicationRecord
  self.table_name = "client"
  has_many :scale
end

measurely-api/archive/scala-api/app/models/clinician.rb
class Clinician < ApplicationRecord
end

measurely-api/archive/scala-api/app/models/scale.rb
class Scale < ApplicationRecord
  self.table_name = "scale"
  belongs_to :client
end

measurely-api/archive/scala-api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :debugpoint

  def debugpoint
  	# byebug
  end
end

measurely-api/archive/scala-api/app/controllers/auth0_controller.rb
# app/controllers/auth0_controller.rb

class Auth0Controller < ApplicationController
  def callback
    # This stores all the user information that came from Auth0
    # and the IdP
    session[:userinfo] = request.env['omniauth.auth']

    # Redirect to the URL you want after successful auth
    redirect_to '/clients'
  end

  def failure
    # show a failure page or redirect to an error page
    @error_msg = request.params['message']
  end
end

measurely-api/archive/scala-api/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  include Secured
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  def index
    @clients = Client.all
    @user = session[:userinfo]
    @clinician_id = @user['uid']
    @clinician_id.to_s
    @clinician_id = @clinician_id[6..30]
    clinicican = params[:clinicican]
    @clients = @clients.where("clinician_id = '#{@clinician_id}'", clinicican)
  end

  # GET /clients/1
  def show
    @clients = Client.find(params[:id])
    @user = session[:userinfo]
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to @client, notice: 'Client was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /clients/1
  def update
    if @client.update(client_params.permit(:first_name, :last_name, :sex, :birth_date, :postcode, :marital_status, :sexuality, :ethnicity, :indigenous, :children, :workforce_status))
      redirect_to @client, notice: 'Client was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /clients/1
  def destroy
    @client.destroy
    redirect_to clients_url, notice: 'Client was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
      @user = session[:userinfo]
    end

    # Only allow a trusted parameter "white list" through.
    def client_params
      params.fetch(:client, {})
    end
end

measurely-api/archive/scala-api/app/controllers/concerns/secured.rb
# app/controllers/concerns/secured.rb

module Secured
  extend ActiveSupport::Concern

  included do
    before_action :logged_in_using_omniauth?
  end

  def logged_in_using_omniauth?
    redirect_to '/' unless session[:userinfo].present?
  end
end

measurely-api/archive/scala-api/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

measurely-api/archive/scala-api/app/controllers/scale_controller.rb
class ScaleController < ApplicationController
include Secured
  before_action :set_scale, only: [:show, :edit, :update, :destroy]

  # GET /scales
  def index
    @scales = Scale.all.order('date DESC')
    @user = session[:userinfo]
    @clinician_id = @user['uid']
    @clinician_id.to_s
    @clinician_id = @clinician_id[6..30]
    clinicican = params[:clinicican]
  	@scales = @scales.where("clinician_id = '#{@clinician_id}'", clinicican)
  	# add_clients
  	# sql = "SELECT * FROM scale INNER JOIN client ON client.client_id = scale.client_id WHERE (scale.client_id = client.client_id) ORDER BY scale.date;"
  	# @scaleclients = ActiveRecord::Base.connection.exec_query(sql)
  end

  # GET /scales/1
  def show
    @scales = Scale.find(params[:id])
    @user = session[:userinfo]
  end

  # GET /scales/new
  def new
    @scale = Scale.new
  end

  # GET /scales/1/edit
  def edit
    @scale = Scale.find(params[:id])
  end

  # POST /scales
  def create
    @scale = Scale.new(scale_params)

    if @scale.save
      redirect_to @scale, notice: 'Scale was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /scales/1
  def update
    if @scale.update(scale_params.permit(:date, :score))
      redirect_to @scale, notice: 'Scale was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /scales/1
  def destroy
    @scale.destroy
    redirect_to scale_url, notice: 'Scale was successfully destroyed.'
  end

  def add_clients
  	@clients = Client.all
  	@clinician_id = @user['uid']
    @clinician_id.to_s
    @clinician_id = @clinician_id[6..30]
    clinicican = params[:clinicican]
  	@clients = @clients.where("clinician_id = '#{@clinician_id}'", clinicican)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scale
      @scale = Scale.find(params[:id])
      # @client = @scale.client
      @user = session[:userinfo]
    end

    # Only allow a trusted parameter "white list" through.
    def scale_params
      params.fetch(:scale, {})
    end
end

measurely-api/archive/scala-api/app/helpers/application_helper.rb
module ApplicationHelper
end

measurely-api/archive/scala-api/app/helpers/clients_helper.rb
module ClientsHelper
end

measurely-api/archive/scala-api/app/helpers/home_helper.rb
module HomeHelper
end

measurely-api/archive/scala-api/app/helpers/scale_helper.rb
module ScaleHelper
end

measurely-api/archive/scala-api/app/views/home/show.html.erb
<!-- app/views/home/show.html.erb -->
<!doctype html>
<html lang="en">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Bootstrap CSS -->
		<link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
		<title>Clients Update Page</title>
	</head>
	<body>
<div class="text-center">
<h1>Scala Database Tool</h1>
<br>
<p>Please click below to login</p>
<br>
<!-- <button href="/auth/auth0" type="button" class="btn btn-primary">Login</button> -->
<a href="/auth/auth0">Login</a>
</div>
</body>
<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	</body>
</html>

measurely-api/archive/scala-api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScalaApi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

measurely-api/archive/scala-api/app/views/scale/_form.html.erb
<%= form_with(model: scale, local: true) do |form| %>
  <% if scale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scale.errors.count, "error") %> prohibited this scale from being saved:</h2>

      <ul>
      <% scale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

measurely-api/archive/scala-api/app/views/scale/create.html.erb
<h1>Scale#create</h1>
<p>Find me in app/views/scale/create.html.erb</p>

measurely-api/archive/scala-api/app/views/scale/edit.html.erb
<!doctype html>
<html lang="en">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Bootstrap CSS -->
		<link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
		<title>Scale Update Page</title>
	</head>
	<body>
		<%= bootstrap_form_for(@scale) do |f| %>
		<table class="container">
			<tbody>
					<div class="form-group container">
						<h1>Edit Scale Record</h1>
						
							<%= link_to 'Return to scale page', scale_path %>
							<p>
								<%= f.submit "Update Scale" %>
							</p>
							<p>
								<%= f.text_field :date %>
							</p>
							<p>
								<%= f.text_field :score %>
							</p>
					</div>
				</tbody>
			</table>
			<% end %>
			<!-- Optional JavaScript -->
			<!-- jQuery first, then Popper.js, then Bootstrap JS -->
			<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
			<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		</body>
		<br>
	</html>

measurely-api/archive/scala-api/app/views/scale/index.html.erb
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
        <title>Scale Datatable</title>
    </head>
    <body>
        <h1>Scala: Scale View</h1>
        <h5>Welcome, <%= @user['info']['name'] %></h5>
    </div>
</div>
<h5><small class="text-muted">Update your existing client's scales in the Scala system.</small></h5>
<%= link_to 'Return to Scala application' %>
<%= link_to 'Edit client information', clients_path %>
<br>
<div class="table-responsive">
    <table id="table_id" class="table table-hover table-bordered table table-striped">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Client ID</th>
                <th scope="col">Measure</th>
                <th scope="col">Subscale</th>
                <th scope="col">Date</th>
                <th scope="col">Score</th>
                <th scope="col">Edit Record</th>
                <th scope="col">Delete Record</th>
            </tr>
        </thead>
        <tbody>
            <% @scales.each do |scale| %>
                <tr>
                <td><%= scale.client_id %></td>
                <td><%= scale.measure %></td>
                <td><%= scale.subscale %></td>
                <td><%= scale.date %></td>
                <td><%= scale.score %></td>
                <td><%= link_to 'Edit', edit_scale_path(scale) %></td>
                <td><%= link_to 'Delete', scale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
<script type="text/javascript">
$(document).ready( function () {
$('#table_id').DataTable();
} );
</script>
</body>
<br>
</html>

measurely-api/archive/scala-api/app/views/scale/new.html.erb
<h1>Scale#new</h1>
<p>Find me in app/views/scale/new.html.erb</p>

measurely-api/archive/scala-api/app/views/scale/show.html.erb
<!doctype html>
<html lang="en">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Bootstrap CSS -->
		<link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
		<title>Scale Update Page</title>
	</head>
	<body>
		<div class="text-center">
			<h3><small id="notice"><%= notice %> </small></h3>
			<%= link_to 'Edit', edit_scale_path(@scale) %> |
			<%= link_to 'Back', scale_path %>
		</div>
		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	</body>
</html>