measurely-api/archive/scala-api_v3/config/routes.rb
Rails.application.routes.draw do
  root 'home#show'
  get 'home/show'
  get 'auth/oauth2/callback' => 'auth0#callback'
  get 'auth/failure' => 'auth0#failure'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :scale
  match 'scale', to: 'scale#update', via: [:patch, :put]
  resources :clients
  match 'clients', to: 'clients#update', via: [:patch, :put]
  # root :to => 'scale#index'
end

measurely-api/archive/scala-api_v3/app/models/analytics_posttherapy.rb
class AnalyticsPosttherapy < ApplicationRecord
end

measurely-api/archive/scala-api_v3/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

measurely-api/archive/scala-api_v3/app/models/client.rb
class Client < ApplicationRecord
  self.table_name = 'client'
  self.primary_key = 'client_id'
  has_many :scales, dependent: :destroy
  
  scope :clinician_id_equals, -> (clinician_id) { where(clinician_id: clinician_id) if clinician_id.present? }
end

measurely-api/archive/scala-api_v3/app/models/clinician.rb
class Clinician < ApplicationRecord
end

measurely-api/archive/scala-api_v3/app/models/scale.rb
class Scale < ApplicationRecord
  self.table_name = 'scale'
  self.primary_key = 'client_id'
  scope :clinician_id_equals, ->(clinician_id) { where(clinician_id: clinician_id) if clinician_id.present? }
  belongs_to :client

  def first_name
    client.first_name
  end

  def last_name
    client.last_name
  end
end

measurely-api/archive/scala-api_v3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :debugpoint

  def debugpoint
  	# byebug
  end

  def set_user
	  @user = session[:userinfo]
	  unless @user['uid'].nil?
	    @clinician_id = @user['uid'].to_s[6..30]
	  end
    end
end

measurely-api/archive/scala-api_v3/app/controllers/auth0_controller.rb
# app/controllers/auth0_controller.rb

class Auth0Controller < ApplicationController
  def callback
    # This stores all the user information that came from Auth0
    # and the IdP
    session[:userinfo] = request.env['omniauth.auth']

    # Redirect to the URL you want after successful auth
    redirect_to '/clients'
  end

  def failure
    # show a failure page or redirect to an error page
    @error_msg = request.params['message']
  end
end

measurely-api/archive/scala-api_v3/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  include Secured
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  def index
    @clients = Client.clinician_id_equals(@clinician_id)
    @user = session[:userinfo]
  end

  # GET /clients/1
  def show
    @clients = Client.find(params[:id])
    @user = session[:userinfo]
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to @client, notice: 'Client was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /clients/1
  def update
    if @client.update(client_params.permit(:first_name, :last_name, :sex, :birth_date, :postcode, :marital_status, :sexuality, :ethnicity, :indigenous, :children, :workforce_status))
      redirect_to @client, notice: 'Client was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /clients/1
  def destroy
    @client.destroy
    redirect_to clients_url, notice: 'Client was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
      @user = session[:userinfo]
    end

    # Only allow a trusted parameter "white list" through.
    def client_params
      params.fetch(:client, {})
    end
end

measurely-api/archive/scala-api_v3/app/controllers/concerns/secured.rb
# app/controllers/concerns/secured.rb

module Secured
  extend ActiveSupport::Concern

  included do
    before_action :logged_in_using_omniauth?
  end

  def logged_in_using_omniauth?
    redirect_to '/' unless session[:userinfo].present?
  end
end

measurely-api/archive/scala-api_v3/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

measurely-api/archive/scala-api_v3/app/controllers/scale_controller.rb
class ScaleController < ApplicationController
include Secured
  before_action :set_scale, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:index, :show]

  # GET /scales
  def index
    @scales = Scale.clinician_id_equals(@clinician_id).includes(:client)
    # @scales = @scales.where(client_id: scale_params[:client_id]) if scale_params[:client_id].present?
    @user = session[:userinfo]
  end

  # GET /scales/1
  def show
    @scales = Scale.find(params[:id])
    @user = session[:userinfo]
  end

  # GET /scales/new
  def new
    @scale = Scale.new
  end

  # GET /scales/1/edit
  def edit
    @scale = Scale.find(params[:id])
  end

  # POST /scales
  def create
    @scale = Scale.new(scale_params)

    if @scale.save
      redirect_to @scale, notice: 'Scale was successfully created.'
    else
      render :new
    end
  end

# PATCH/PUT /scales/1
  def update
    if @scale.update(scale_params.permit(:date, :score))
      redirect_to scale_index_path, notice: 'Scale was successfully updated.'
    else
      render :edit
    end
      # redirect_to(action: :index) #, notice: 'Scale was successfully updated.'
      # redirect_to scale_index_path
  end

  # DELETE /scales/1
  def destroy
    @scale.destroy
    redirect_to scale_index_path, notice: 'Scale was successfully destroyed.'
  end

  def add_clients
  	@clients = Client.all
  	@clinician_id = @user['uid']
    @clinician_id.to_s
    @clinician_id = @clinician_id[6..30]
    clinicican = params[:clinicican]
  	@clients = @clients.where("clinician_id = '#{@clinician_id}'", clinicican)
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_scale
      @scale = Scale.find(params[:id])
      @user = session[:userinfo]
    end

    # Only allow a trusted parameter "white list" through.
    def scale_params
      params.require(:scale).permit(client_id: [])
      # params.permit(:client_id)
    end
end

measurely-api/archive/scala-api_v3/app/helpers/application_helper.rb
module ApplicationHelper
end

measurely-api/archive/scala-api_v3/app/helpers/clients_helper.rb
module ClientsHelper
end

measurely-api/archive/scala-api_v3/app/helpers/home_helper.rb
module HomeHelper
end

measurely-api/archive/scala-api_v3/app/helpers/scale_helper.rb
module ScaleHelper
end

measurely-api/archive/scala-api_v3/app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

measurely-api/archive/scala-api_v3/app/views/clients/edit.html.erb
<!doctype html>
<html lang="en">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Bootstrap CSS -->
		<link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
		<title>Clients Update Page</title>
	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #d35400;">
            <a class="navbar-brand" href="#">P s y c h l y t X | Scala: Edit Client Record</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="/clients">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/clients">Return to client page</a>
                    </li>
				</ul>
            </div>
        </nav>
		<%= bootstrap_form_for(@client) do |f| %>
		<table class="container">
			<br>
			<tbody>
					<div class="form-group container">
							<p>
								<%= f.submit "Update Client" %>
							</p>
							<p>
								<%= f.text_field :first_name %>
							</p>
							<p>
								<%= f.text_field :last_name %>
							</p>
							<p>
								<%= f.select :sex, [["Male", "Male"], ["Female", "Female"], ["Other", "Other"]] %>
							</p>
							<p>
								<%= f.text_field :birth_date %>
							</p>
							<p>
								<%= f.text_field :postcode %>
							</p>
							<p>
								<%= f.select :marital_status, [["Never Married", "Never Married"], ["Currently Married", "Currently Married"], ["Separated", "Separated"], ["Divorced", "Divorced"], ["Widowed", "Widowed"], ["Cohabiting", "Cohabiting"]] %>
							</p>
							<p>
								<%= f.select :sexuality, [["Heterosexual", "Heterosexual"], ["Gay", "Gay"], ["Bisexual", "Bisexual"], ["Lesbian", "Lesbian"], ["Transgender", "Transgender"], ["Queer", "Queer"], ["Other", "Other"] ] %>
							</p>
							<p>
								<%= f.select :ethnicity, [["Caucasian", "Caucasian"], ["Latino/Hispanic", "Latino/Hispanic"], ["Middle Eastern", "Middle Eastern"], ["African", "African"], ["Caribbean", "Caribbean"], ["South Asian", "South Asian"], ["East Asian", "East Asian"], ["Mixed", "Mixed"], ["Other", "Other"]] %>
							</p>
							<p>
								<%= f.select :indigenous, [["Yes", "TRUE"], ["No", "FALSE"]] %>
							</p>
							<p>
								<%= f.number_field :children %>
							</p>
							<p>
								<%= f.select :workforce_status, [["Working Full-Time", "Working Full-Time"], ["Working Part-Time", "Working Part-Time"], ["Working Casual Hours", "Working Casual Hours"], ["Studying", "Studying"], ["Unemployed", "Unemployed"], ["Retired", "Retired"]] %>
							</p>
							<p>
								<%= f.select :education, [["No Education", "No Education"], ["Primary Education", "Primary Education"], ["Secondary Education", "Secondary Education"], ["Post-Secondary/Teriary Education", "Post-Secondary/Teriary Education"], ["Bachlor or Equivalent", "Bachlor or Equivalent"], ["Master or Equivalent", "Master or Equivalent"], ["Doctoral Equivalent", "Doctoral Equivalent"]] %>
							</p>
					</div>
				</tbody>
			</table>
			<% end %>
			<!-- Optional JavaScript -->
			<!-- jQuery first, then Popper.js, then Bootstrap JS -->
			<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
			<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		</body>
		<br>
	</html>

measurely-api/archive/scala-api_v3/app/views/clients/index.html.erb
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
        <title>Clients Datatable</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #d35400;">
            <a class="navbar-brand" href="">P s y c h l y t X | Scala: Client View</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">Return to Scala application</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/scale">Edit my client's outcomes</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-text" >Welcome, <%= @user['info']['name'] %></a>
                    </li>
                </ul>
            </div>
        </nav>
        <br>
        <div class="table-responsive">
            <table id="table_id" class="table table-hover table-bordered table table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Client ID</th>
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Sex</th>
                        <th scope="col">Birth Date</th>
                        <th scope="col">Postcode</th>
                        <th scope="col">Marital Status</th>
                        <th scope="col">Sexuality</th>
                        <th scope="col">Ethnicity</th>
                        <th scope="col">Indigenous</th>
                        <th scope="col">Children</th>
                        <th scope="col">Workforce Status</th>
                        <th scope="col">Education</th>
                        <th scope="col">Edit Record</th>
                        <th scope="col">Delete Record</th>
                    </tr>
                </thead>
                <tbody>
                    <% @clients.each do |client| %>
                    <tr>
                        <td><%= client.client_id %></td>
                        <td><%= client.first_name %></td>
                        <td><%= client.last_name %></td>
                        <td><%= client.sex %></td>
                        <td><%= client.birth_date %></td>
                        <td><%= client.postcode %></td>
                        <td><%= client.marital_status %></td>
                        <td><%= client.sexuality %></td>
                        <td><%= client.ethnicity %></td>
                        <td><%= client.indigenous %></td>
                        <td><%= client.children %></td>
                        <td><%= client.workforce_status %></td>
                        <td><%= client.education %></td>
                        <td><%= link_to 'Edit', edit_client_path(client) %></td>
                        <td><%= link_to 'Delete', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
        <script type="text/javascript">
        $(document).ready( function () {
        $('#table_id').DataTable();
        } );
        </script>
    </body>
    <br>
</html>

measurely-api/archive/scala-api_v3/app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

measurely-api/archive/scala-api_v3/app/views/clients/show.html.erb
<!doctype html>
<html lang="en">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Bootstrap CSS -->
		<link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
		<title>Clients Update Page</title>
	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #d35400;">
            <a class="navbar-brand" href="#">P s y c h l y t X | Scala: Edit Client Record</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="/clients">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/clients">Return to client page</a>
                    </li>
				</ul>
            </div>
        </nav>
		<div class="text-center">
			<br>
			<h2>Record has been updated sucessfully.</h2>	
		</div>
		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	</body>
</html>

measurely-api/archive/scala-api_v3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScalaApi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

measurely-api/archive/scala-api_v3/app/views/scale/_form.html.erb
<%= form_with(model: scale, local: true) do |form| %>
  <% if scale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scale.errors.count, "error") %> prohibited this scale from being saved:</h2>

      <ul>
      <% scale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

measurely-api/archive/scala-api_v3/app/views/scale/create.html.erb
<h1>Scale#create</h1>
<p>Find me in app/views/scale/create.html.erb</p>

measurely-api/archive/scala-api_v3/app/views/scale/index.html.erb
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
        <title>Scale Datatable</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #d35400;">
            <a class="navbar-brand" href="#">P s y c h l y t X | Scala: Measure View</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Return to Scala application</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/clients">Edit client information </a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-text" >Welcome, <%= @user['info']['name'] %></a>
                    </li>
                </ul>
            </div>
        </nav>
        <br>
        <div class="table-responsive">
            <table id="table_id" class="table table-hover table-bordered table table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Client ID</th>
                        <th scope="col">Measure</th>
                        <th scope="col">Subscale</th>
                        <th scope="col">Date</th>
                        <th scope="col">Score</th>
                        <th scope="col">Edit Record</th>
                        <th scope="col">Delete Record</th>
                    </tr>
                </thead>
                <tbody>
                    <% @scales.each do |scale| %>
                    <tr>
                        <td><%= scale.client.first_name %></td>
                        <td><%= scale.client.last_name %></td>
                        <td><%= scale.client_id %></td>
                        <td><%= scale.measure %></td>
                        <td><%= scale.subscale %></td>
                        <td><%= scale.date %></td>
                        <td><%= scale.score %></td>
                        <td><%= link_to 'Edit', edit_scale_path(scale) %></td>
                        <td><%= link_to 'Delete', scale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
        <script type="text/javascript">
        $(document).ready( function () {
        $('#table_id').DataTable();
        } );
        </script>
    </body>
    <br>
</html>

measurely-api/archive/scala-api_v3/app/views/scale/new.html.erb
<h1>Scale#new</h1>
<p>Find me in app/views/scale/new.html.erb</p>